### ISSUE TITLE
AraNetNode2vec

### ISSUE THREAD

**Issue by Lsz-20** [miderxi/arapathogen2#1]
Hello, I try to run ./AraNetNode2vec/generate_node2vec.py to generate features, but it seems miss the 'ara_node2vec_feature.txt'?

**Comment by miderxi** [comment]
我已收到邮件，会尽快处理。

**Comment by miderxi** [comment]
script_path = sys.path[0]
input_file  = f"../AraNetStruc2vec/Intact_TAIR_protein_interaction.txt"
output_file = f"./AraNet_node2vec_256.pkl"

main(input_file=input_file, output_file=output_file)

The AraNet_node2vec output feature is a python dict object and save with pickle format.
